### ISSUE TITLE
Versioning confusion

### ISSUE THREAD

**Issue by skyf0l** [pavpanchekha/setup-z3#12]
The latest published version on the [marketplace](https://github.com/marketplace/actions/install-z3) is `1.2.2` but this version doesn't support the `distribution` argument. However, the latest [release](https://github.com/pavpanchekha/setup-z3/releases) (`0.3.0`) does.
You may have been confused with versioning. Can you update the latest version on the marketplace please?

**Comment by pavpanchekha** [comment]
I believe this is done.
