### ISSUE TITLE
Check failure: The `add-path` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by rachelcarmena** [pavpanchekha/setup-z3#4]
Hi @pavpanchekha :wave: 

Thank you so much for your action :raised_hands: 

### Request

Please, could you create a new release ?

### Reason

![Screenshot from 2020-11-04 15-37-37](https://user-images.githubusercontent.com/22792183/98128369-22b47680-1eb8-11eb-8e9a-5fff1e9280d8.png)

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

And #3 made the required upgrade.

We removed all the commands when using your action and if it's not fixed we'll have to add the commands again.

Thanks in advance!

**Comment by pavpanchekha** [comment]
I think I just did, please reopen the issue if it didn't work for some reason.

**Comment by rachelcarmena** [comment]
Thank you so much @pavpanchekha :raised_hands: 

I don't understand it because 2 annotations appear now:

![Screenshot from 2020-11-05 19-27-04](https://user-images.githubusercontent.com/22792183/98281838-95e3e880-1f9d-11eb-9722-27c581818879.png)

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

> The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

They also appear in the check for this repository:

https://github.com/pavpanchekha/setup-z3/actions/runs/347890020

I'll let you know if I find the reason. Thanks again for your quick response!!
